sudo: false
dist: trusty
install:
 - mvn clean
script:
 - mvn -B -fae -Dserver.version=$SERVER_VERSION install -Dipv6

language: java
jdk:
  - oraclejdk8
  - oraclejdk10
env:
  - SERVER_VERSION=13.0.0.Final
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
  - sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts'
  - ifconfig
