# This workflow is for a nightly run against WildFly upstream

name: WildFly Test Build

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

jobs:
  wildfly-build:
    runs-on: ubuntu-latest
    outputs:
      wildfly-version: ${{steps.version.outputs.wildfly-version}}
    steps:
      - name: Checkout WildFly
        uses: actions/checkout@v2
        with:
          repository: wildfly/wildfly
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - name: Build WildFly
        run: 'mvn clean install -pl :wildfly-dist -am -DskipTests -Denforcer.skip -Dcheckstyle.skip -Drelease'
      - id: version
        run: echo "::set-output name=wildfly-version::$(mvn -B help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"
      - name: Archive the server
        run: |
            cd ./dist/target
            mv wildfly-*-SNAPSHOT server
            zip -r ~/server.zip server
      - uses: actions/upload-artifact@v2
        with:
          name: server
          path: ~/server.zip
          retention-days: 5

  resteasy-build:
    runs-on: ${{ matrix.os }}
    needs: wildfly-build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['11', '17']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: maven-repository
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Copy server - Linux
        if: runner.os == 'Linux'
        run: unzip -o ./server.zip
      - name: Build with Maven Java ${{ matrix.java }}
        run: mvn clean install '-Dserver.home=`pwd`/server'
      - name: Upload surefire reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'
      - name: Upload server logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/*.log'
